sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: nxYwg4eevf1qzeH+vZuiTK2I0nhQbjZmmnvkzQ6kgUAo0dOqqytsG5LOPwJbI0hXA/nwUT72fL1ik9lLExMtpD1uo1Wmat8UPkxmC7MH4q+IM6n7S5MspnG8tAlNMXF+vIumtn4El4lWsBn0YKqrTtBhgEQ1kf153MI+iJx4uwEXxk0d752RavA1rla1zjl9TSBwJ0uOl8TWctBNkx0MKbxzlE1KFti1ECejqDpgcRq+LJciiQscdNeUNEw0pjyRgTU4gZkrQWhdVGO1ZlEN3vMurDvJz8GAAIRYoCiuIt9ubJdBQf4cKD4qzd7bd3lJ1UBAiilNSgIdRnqUZkRZeHjHgNnKtZGdvUubkFm9ke8I5/pJFxK7ggu3BG0I+P/MKjePYaqyTW0K39BgBa8jFl3AgPvJJZNDt30GTNkkzYbAqmp6kWCRGR6M28K55zK0KLbWZ6Hr1+D75qM/urEmrqxMB5CKRNV6uAsGNuE1BGshp7kS9KKUlbFncvmqi/F/inyjzHfsx2Yk4F8hJ/hVe5tZSleazdMQ1WGt3IGyjqlJ5zs8jzoS68rhVyDtwnNMxPOl0TV9bNpenKnuTH7dJBh2k8rQl1V+Kxw/vCXruP/ki4OskXk+hqOHJK+vpVXCtRQLoI2HsZsvELslcIAvmRpLMdTXPwhPVGFwkLkz4zc=
